export const mockItems = [
  {
    category: "Fruits",
    currency: "EUR",
    description: "Fresh and delicious apples from the local orchard.",
    id: 1,
    name: "Apple",
    price: 1.1,
  },
  {
    category: "Fruits",
    currency: "EUR",
    description: "Ripe and sweet bananas, perfect for a healthy snack.",
    id: 2,
    name: "Banana",
    price: 0.65,
  },
  {
    category: "Meat",
    currency: "EUR",
    description:
      "Boneless and skinless chicken breasts, great for grilling or baking.",
    id: 3,
    name: "Chicken Breast",
    price: 3.25,
  },
  {
    category: "Seafood",
    currency: "EUR",
    description: "Fresh Atlantic salmon fillet, high in omega-3 fatty acids.",
    id: 4,
    name: "Salmon",
    price: 6.99,
  },
  {
    category: "Bakery",
    currency: "EUR",
    description: "Artisanal whole grain bread, freshly baked daily.",
    id: 5,
    name: "Bread",
    price: 2.05,
  },
  {
    category: "Dairy",
    currency: "EUR",
    description: "Farm-fresh whole milk, rich and creamy.",
    id: 6,
    name: "Milk",
    price: 1.79,
  },
  {
    category: "Dairy",
    currency: "EUR",
    description: "Organic free-range eggs, a breakfast essential.",
    id: 7,
    name: "Eggs",
    price: 1.35,
  },
  {
    category: "Vegetables",
    currency: "EUR",
    description: "Vine-ripened tomatoes, perfect for salads and sandwiches.",
    id: 8,
    name: "Tomato",
    price: 0.65,
  },
  {
    category: "Vegetables",
    currency: "EUR",
    description: "Crisp and refreshing cucumbers, great for salads.",
    id: 9,
    name: "Cucumber",
    price: 0.89,
  },
  {
    category: "Sweets",
    currency: "EUR",
    description: "A decadent dark chocolate bar with almonds.",
    id: 10,
    name: "Chocolate Bar",
    price: 1.95,
  },
  {
    category: "Pasta",
    currency: "EUR",
    description: "Italian-style pasta, perfect for your favorite sauces.",
    id: 11,
    name: "Pasta",
    price: 1.35,
  },
  {
    category: "Vegetables",
    currency: "EUR",
    description: "Crisp and fresh lettuce for salads and sandwiches.",
    id: 12,
    name: "Lettuce",
    price: 1.15,
  },
  {
    category: "Beverages",
    currency: "EUR",
    description: "100% pure orange juice, packed with vitamins.",
    id: 13,
    name: "Orange Juice",
    price: 2.49,
  },
];
